version: '3.8'

# Services
services:

    # Nginx Service
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
            args:
                UID: ${XUID} #UID is a read-only variable in bash (reserved variable)
                GID: ${XGID}
        container_name: ${APP_NAME:?err}-nginx
        #user: "${XUID}:${XGID}"
        ports:
            - 8080:80
            - 443:443
        volumes:
            - type: bind
              source: src/
              target: /var/www/html
            - type: bind
              source: configurations/nginx/sites-enabled
              target: /etc/nginx/sites-enabled
            - type: bind
              source: logs/nginx/
              target: /var/log/nginx/

    #Php-Fpm service
   # php:

