version: '3.8'

# Services
services:

    #Nginx Service
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
            args:
                UID: ${XUID} #UID is a read-only variable in bash (reserved variable)
                GID: ${XGID}
        container_name: ${APP_NAME:?err}-nginx
        #user: "${XUID}:${XGID}"
        ports:
            - '8080:80'
            - '443:443'
        volumes:
            - type: bind
              source: src/
              target: /var/www/html
            - type: bind
              source: configurations/nginx/sites-available
              target: /etc/nginx/sites-available
            - type: bind
              source: logs/nginx/
              target: /var/log/nginx/

    #Php-fpm service
    php:
        build:
            context: .
            dockerfile: docker/php.Dockerfile
            args:
                UID: ${XUID} #UID is a read-only variable in bash (reserved variable)
                GID: ${XGID}
        container_name: ${APP_NAME:?err}-php
        ports:
            - '9000:9000'
        env_file:
            - '.env'
        volumes:
            - type: bind
              source: src/
              target: /var/www/html
            - '/var/www/html/vendor/'
            - type: bind
              source: logs/php/
              target: /var/log/php/

    #Mysql service
    mysql:
        build:
            context: .
            dockerfile: docker/mysql.Dockerfile
            args:
                UID: ${XUID} #UID is a read-only variable in bash (reserved variable)
                GID: ${XGID}
        #command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
        container_name: ${APP_NAME:?err}-mysql 
        ports:
            - '3306:3306'
        env_file:
            - '.env'
        volumes:
            - type: bind
              source: logs/mysql/
              target: /var/log/mysql/
            - "./docker/initScripts/:/docker-entrypoint-initdb.d/"
            - 'mysqldata:/var/lib/mysql'

# Volumes
volumes:
  mysqldata:
