version: '3.8'

# Services
services:

    # Nginx Service
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
            args:
                UID: ${XUID} #UID is a read-only variable in bash (reserved variable)
                GID: ${XGID}
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - 8080:80
